# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: book_parser.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'book_parser.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x62ook_parser.proto\x12\nbookparser\"\\\n\x04\x42ook\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0c\x61vailability\x18\x02 \x01(\t\x12\x0b\n\x03upc\x18\x03 \x01(\t\x12\x16\n\x0eprice_excl_tax\x18\x04 \x01(\x01\x12\x0b\n\x03tax\x18\x05 \x01(\x01\" \n\x10ParseBookRequest\x12\x0c\n\x04html\x18\x01 \x01(\t\"3\n\x11ParseBookResponse\x12\x1e\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x10.bookparser.Book2]\n\x11\x42ookParserService\x12H\n\tParseBook\x12\x1c.bookparser.ParseBookRequest\x1a\x1d.bookparser.ParseBookResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'book_parser_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOK']._serialized_start=33
  _globals['_BOOK']._serialized_end=125
  _globals['_PARSEBOOKREQUEST']._serialized_start=127
  _globals['_PARSEBOOKREQUEST']._serialized_end=159
  _globals['_PARSEBOOKRESPONSE']._serialized_start=161
  _globals['_PARSEBOOKRESPONSE']._serialized_end=212
  _globals['_BOOKPARSERSERVICE']._serialized_start=214
  _globals['_BOOKPARSERSERVICE']._serialized_end=307
# @@protoc_insertion_point(module_scope)
